<?php
	/**
	 * ----------------------------------------
	 * | Created By pfinal-collection                 |
	 * | User: pfinal <lampxiezi@163.com>     |
	 * | Date: 2019/10/15                      |
	 * | Time: 上午11:33                        |
	 * ----------------------------------------
	 * |    _____  ______ _             _     |
	 * |   |  __ \|  ____(_)           | |    |
	 * |   | |__) | |__   _ _ __   __ _| |    |
	 * |   |  ___/|  __| | | '_ \ / _` | |    |
	 * |   | |    | |    | | | | | (_| | |    |
	 * |   |_|    |_|    |_|_| |_|\__,_|_|    |
	 * ----------------------------------------
	 */
	
	namespace tests;
	
	use pf\collection\Collection;
	use PHPUnit\Framework\TestCase;
	
	class BaseTest extends TestCase
	{
		public function setUp()
		{
			parent::setUp(); // TODO: Change the autogenerated stub
		}
		
		public function testBase()
		{
			$collection = Collection::make(
				['name' => 'PFinal社区', 'url' => 'https://friday-go.cc/']
			);
			$this->assertEquals('PFinal社区', $collection['name']);
		}
	}